In [3]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
#2dimentional array
arr_2d=np.array([[1,2],[3,4]])
print(arr_2d)

[1 2 3]
[[1 2]
 [3 4]]


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("shape of the array:",arr.shape)  #gives the size of the array
print("size of the array:",arr.size) #gives the size of the array
print("dimension of the array:",arr.ndim) #shows the dimention of the array

shape of the array: (2, 3)
size of the array: 6
dimension of the array: 2


In [11]:
#reshaping of an array

import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped_arr =arr.reshape(2,3) #reshapes the array into 2,3
print(reshaped_arr)
reshaped_arr =arr.reshape(3,2) #reshapes the array into 3,2
print(reshaped_arr)
reshaped_arr =arr.reshape(2,3) #
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
flattened_arr=arr_2d.flatten()
print(flattened_arr)


[1 2 3 4 5 6]


In [9]:
import numpy as np
arr=int(input("enter the list"))
arr_2=int(input("enter the list"))
print([arr])
print([arr_2])
reshaped_arr=np.array([[arr],[arr_2]])
print(reshaped_arr)
reshaped_arr=np.array([[arr_2],[arr]])
print(reshaped_arr)

enter the list 1
enter the list 2


[1]
[2]
[[1]
 [2]]
[[2]
 [1]]


In [11]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[2])
print(arr[1:4])
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1:,:3])

30
[20 30 40]
[[4 5 6]
 [7 8 9]]


In [13]:
import numpy as np
arr=np.arange(0,10,2)
print(arr)
arr=np.linspace(0,1,5)
print(arr)
arr=np.logspace(1,3,4)
print(arr)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  10.           46.41588834  215.443469   1000.        ]


In [15]:
import numpy as np
zeros=np.zeros([2,3])
print(zeros)
ones=np.ones([2,3])
print(ones)
identity=np.eye(4,dtype=int)
print(identity)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [17]:
import numpy as np
random_floats=np.random.rand(2,3)
print(random_floats)
random_ints=np.random.randint(1,10,(3,3))
print(random_ints)

[[0.65730392 0.57112709 0.43553043]
 [0.62134426 0.93940909 0.70762786]]
[[9 7 2]
 [3 6 1]
 [2 5 7]]


## import numpy as np
start = int(input("Enter start value: "))
end = int(input("Enter end value: "))
step = int(input("Enter step value: "))
arr = np.arange(start, end, step)
print(arr)
start = int(input("Enter start value: "))
end = int(input("Enter end value: "))
step = int(input("Enter number of samples: "))  
arr_1 = np.linspace(start, end, step)
print(arr_1)
start = int(input("Enter start value: "))
end = int(input("Enter end value: "))
step = int(input("Enter number of samples: "))  
arr = np.logspace(start, end, step)
print(arr_2)
    

In [20]:
import numpy as np
zeros=np.zeros([2,3],"i")
print(zeros)
ones=np.ones([2,3],"i")
print(ones)
identity=np.eye(3,dtype=int)
print(identity)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
import numpy as np
r=int(input("enter row:"))
c=int(input("enter col:"))
r1=int(input("matrix:"))
c1=int(input("martix2:"))
zeros=np.zeros([r,c],"i")
print(zeros)
random_f=np.random.rand(r,c)
print(random_f)
print(np.random.randint(r,c,(r1,c1)))

enter row: 1 2 3


ValueError: invalid literal for int() with base 10: '1 2 3'

In [24]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [26]:
import numpy as np
a=np.array(([[1,2],[3,4]]))
b=np.array([[5,6],[7,8]])
result=np.dot(a,b)
print(result)


[[19 22]
 [43 50]]


In [28]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [30]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("minimum:",np.min(arr))
print("maximum:",np.max(arr))
print("mean:",np.mean(arr))

sum: 21
minimum: 1
maximum: 6
mean: 3.5


In [32]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))
print(np.mean(arr,axis=1,dtype=int))


[5 7 9]
[2 5]


In [34]:
import numpy as np
arr=np.array([1,2,3,4])
print(np.cumsum(arr))
print(np.cumprod(arr))


[ 1  3  6 10]
[ 1  2  6 24]


In [36]:
import numpy as np
arr=np.array([10,3,7,1])
sorted_arr=np.sort(arr)
print(sorted_arr)
sorted_indices=np.argsort(arr)
print(sorted_indices)

[ 1  3  7 10]
[3 1 2 0]


In [ ]:
import numpy as np
arr=np.array([1,2,3,2,2,3,3,3])
unique_elements=np.unique(arr)
print(unique_elements)

In [ ]:
import numpy as np
arr=np.array([10,15,20,25])
indices=np.where(arr>15)
print(indices)
values=arr[np.where(arr>15)]
print(values)


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.transpose(arr))


In [ ]:
import numpy as np
arr=np.array([[1,2],[3,4]])
det = np.linalg.det(arr)
print(det)
inv=np.linalg.inv(arr)
print(inv)


In [ ]:
import numpy as np
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[3,2,1]])
concated=np.concatenate([a,b])
print(concated)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr1=np.array([[11,12,13],[14,15,16],[20,21,23]])
split_arr=np.split(arr,3)
print(split_arr)


In [ ]:
import numpy as np
arr=np.array([[2,7,6],[9,5,1],[4,3,8]])
print("sum:",np.sum(arr))
diagonal=np.diagonal(arr)
print(diagonal)
vstacked=np.vstack([arr])
print(vstacked)
hstacked=np.hstack([arr])
print(hstacked)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.sum(diagonal))


In [ ]:
import numpy as np
a=[]
r=int(input("enter numbers:"))
for i in range(r):
    c=int(input("enter "+str(i+1)+" value:"))
    a.append(c)
arr_2d=np.array(a)
unique_elements=np.unique(arr_2d)
print(unique_elements)
a=np.size(arr_2d)
print(a)
b=np.size(unique_elements)
print(b)
reshaped_arr=arr_2d.reshape(3,3)
print(reshaped_arr)
x=np.sum(reshaped_arr,axis=0)#column
y=np.sum(reshaped_arr,axis=1)
t=np.trace(reshaped_arr)
print(x)
print(y)
if np.unique(x)==np.unique(y)==t:
   print("magic")
else:
   print("not magic")

In [ ]:
import numpy as np
A=[]
A=list(map(lambda x: x, range(0, 10)))
print(A)

In [ ]:
import numpy as np
arr=np.random.randint(1,20,(3,3))
print(arr)
print("sum:",np.sum(arr,axis=1))



In [ ]:
import numpy as np
A=[[1,2],[3,4]]
B=[[5,6],[7,8]]
add=np.add(A,B)
print(add)
mul=np.multiply(A,B)
print(mul)
dot=np.dot(A,B)
print(dot)



In [ ]:
import numpy as np
A=[]
B=[]
A=list(map(lambda x: x, range(1, 5)))
B=list(map(lambda x: x, range(6,10)))
add=np.add(A,B)
print(add)
mul=np.multiply(A,B)
print(mul)
dot=np.dot(A,B)
print(dot)


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("Matrix Multiplication (using dot):\n", result)
result2 = A @ B
print("Matrix Multiplication (using @):\n", result2)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr % 2 == 0
print("Mask for even numbers:", mask)
even_numbers = arr[mask]
print("Even Numbers:", even_numbers)

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
result = arr[indices]
print("Elements at indices 0, 2, 4:", result)

In [ ]:
import numpy as np
angles=np.array([0,np.pi/2,np.pi])
sine_values=np.sin(angles)
cosine_values=np.cos(angles)
tangent_values=np.tan(angles)
print("sine_values:",sine_values)
print("cosine_values:",cosine_values)
print("tangent_values:",tangent_values)

In [ ]:
import numpy as np
arcsin_values=np.arcsin(1)
print("arcsin(1):",np.degrees(arcsin_values))

In [ ]:
import numpy as np
arr=np.array([1,2,3])
exp_values=np.exp(arr)
print("exponential values:",exp_values)
log_values=np.log(arr)
print("Natural log:",log_values)
log10_values=np.log10(arr)
print("log base 10:",log10_values) 

In [ ]:
import numpy as np
arr=np.array([1.56,2.35,3.89])
rounded=np.round(arr)
print("Rounded values:",rounded)
floored=np.floor(arr)
print("floored values:",floored)
ceiled=np.ceil(arr)
print("ceiled values:",ceiled)

In [ ]:
import numpy as np
data=np.array([1,2,3,4,5])
mean_value=np.mean(data)
print("mean:",mean_value)
median_value=np.median(data)
print("median:",median_value)
variance_value=np.var(data)
print("variance:",variance_value)
std_dev_value=np.std(data)
print("standard deviation:",std_dev_value)


In [ ]:
import numpy as np
A=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
B=np.array([8,-11,-3])
x=np.linalg.solve(A,B)
print("solution:",x)

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([2,3])
x=np.linalg.solve(A,B)
print("solution:",x)

In [ ]:
import numpy as np
arr=np.array([1,np.nan,3,4])
nan_check=np.isnan(arr)
print("nan check:",nan_check)
arr_cleaned=np.nan_to_num(arr,nan=-1)
print("cleaned array:",arr_cleaned)

In [ ]:
import time
import numpy as np
arr=np.arange(1e6)
print(arr)
start=time.time()
loop_result=[x**2 for x in arr]
end=time.time()
print("loop time:",end-start)
start=time.time()
vectorized_result=arr**2
end=time.time()
print("numpy time:",end-start)